name: Markdown Checks

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  markdown:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Instalar dependências
        run: |
          npm install -g markdownlint-cli
          npm install -g doctoc

      - name: Verificar formatação Markdown
        run: markdownlint "**/*.md"

      - name: Atualizar sumário no README.md
        run: doctoc README.md --github
